version: '3'

services:
  redis:
    image: redis
    ports: 
      - "6379:6379"
  rabbitmq:
    build:
      context: .
      dockerfile: rabbitmqconf/rabbit.dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
  # api:
  #   build:
  #     context: .
  #     dockerfile: api_instance.dockerfile
  #   ports:
  #      - "5000:5000"
  #   depends_on:
  #     - rabbitmq
  # worker:
  #   build:
  #     context: .
  #     dockerfile: worker_instance.dockerfile
  #   depends_on:
  #     - rabbitmq



